<?php

/**
 * PostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Post');
    }

    public function getLastPosts()
    {
    	$q = $this->createQuery('p');
    	$q->where('p.es_activo = 1');
    	$q->orderBy('p.created_at DESC');

    	return $q->execute();
    }
}